server:
  port: 8080

weather:
  api-key: 3f70ad1c3137c6ecfaa21313f7c8db45

spring:
  liquibase:
    default-schema: public
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5430/weather_db
    username: weather
    password: weather
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect