server:
  port: 8081

weather:
  api-key: 3f70ad1c3137c6ecfaa21313f7c8db45
  url: https://api.openweathermap.org/data/2.5/weather

translator:
  en-url: http://localhost:8080/en/translate

spring:
  liquibase:
    default-schema: public
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5430/weather_db
    username: weather
    password: weather
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

url:
